### ISSUE TITLE
Sprite playback canvas transformation drifts

### ISSUE THREAD

**Issue by MarkussLugia** [JdavisBro/beastieball#9]
The playback canvas `previewcanvas` in Beastiepedia gets different transform style value in paused and playing state.
![IMG_20241121_182144](https://github.com/user-attachments/assets/cb85c197-8bf1-468e-bb65-84380a011839)
![IMG_20241121_182159](https://github.com/user-attachments/assets/2c5e24c4-ba55-4b73-aed8-90f5e5ad83fd)
This causes sprite misalignment.

**Comment by MarkussLugia** [comment]
A quick console debug in `ContentPreview.tsx` shows that `previewcanvas` in paused render cycles uses different `bbox` data than in playing render cycles. This causes `getCrop()` getting and returning the "drifted" transformation style string. 

If it's not intended behavior and you guys also have no idea about this, maybe I can try looking into it later next week.

**Comment by JdavisBro** [comment]
this is on purpose. it uses the sprite's full bbox when paused to not change bbox when changing between frames.
